[이원빈] Feature/space
wecode-bootcamp-korea/31-2nd-GoCloud-backend pull request #12
Opened 2022-04-20 02:18 UTC by Onbin97

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
Host로 등록된 유저의 공간 등록 기능 구현
유저의 Wishlist 기능 구현.

<br />

2022-04-20 07:42 UTC, lordmyshepherd requested changes

2022-04-20 07:42 UTC, lordmyshepherd commented on spaces/urls.py
> +    path('/register', SpaceRegisterView.as_view()),
SpaceRegisterView의 post handler method를 SpaceListView로 옮겨주세요.
```suggestion
    path('/register', SpaceRegisterView.as_view()),

        POST :8000/spaces/register
        POST :8000/spaces
```

2022-04-20 07:42 UTC, lordmyshepherd commented on spaces/views.py
> +class SpaceRegisterView(View):
```suggestion
```

2022-04-20 07:42 UTC, lordmyshepherd commented on spaces/views.py
> +            return JsonResponse({'error' : 'HOST_EXIST_ERROR'})
View class 내부에는 http request, response 관련된 역할만 수행하는 코드만 있어야 합니다.
host인지 아닌지 유무를 판단하는 비지니스 로직(혹은 서비스 로직)은 Model Layer에 있어야 합니다.
```suggestion
```

2022-04-20 07:42 UTC, lordmyshepherd commented on spaces/views.py
> +            self.check_host(user)
```python
# user/models.py

class User(models.Model):
    name = ..
    password = ..
    
    class Meta:
        db_table = 'users'
     
     def is_host(self):
        if not Host.objects.filter(user = user).exists():
            return False
        return True

```

```python
def post(self, request):
    user = request.user

    if not user.is_host():
        return JsonResponse()
```

2022-04-20 07:42 UTC, lordmyshepherd commented on spaces/views.py
> +                return JsonResponse({'message' : 'FILE_UPLOAD_ERROR'}, status = 400)
```suggestion
            if not files:
                return JsonResponse({'message' : 'FILE_UPLOAD_ERROR'}, status = 400)
```

2022-04-20 07:42 UTC, lordmyshepherd commented on spaces/views.py
> +            files = request.FILES.getlist('filename')
```suggestion
            files = request.FILES.getlist('filename', [])
```

2022-04-20 07:42 UTC, lordmyshepherd commented on spaces/views.py
> +                )
하나의 transaction으로 처리해주세요.

2022-04-20 07:42 UTC, lordmyshepherd commented on spaces/views.py
> +                )
1번 방법 - 데코레이터 활용 -> `@transaction.atomic`, 
2번 방법 - context manager를 활용해서 구현 -> `with transaction.atomic(): ..`

2022-04-20 09:06 UTC, lordmyshepherd requested changes

2022-04-20 09:06 UTC, lordmyshepherd commented on spaces/views.py
> +            User.check_host(user)
line 53 코드는 필요 없을 것 같은데요?

2022-04-20 09:06 UTC, lordmyshepherd commented on spaces/views.py
> +            if not User.check_host(user):
```suggestion
            if not user.check_host:
```

2022-04-20 09:06 UTC, lordmyshepherd commented
마이너한 수정사항과 컨플릭트 해결해주세요~

2022-04-21 01:22 UTC, jamessoun93 requested changes

2022-04-21 01:22 UTC, jamessoun93 commented on spaces/views.py
> +                    )
매 iteration마다 `create()`를 하는 것보다 `bulk_create()` 사용해주시면 좋겠네요~

2022-04-21 01:22 UTC, jamessoun93 commented on uploader.py
> +        #         host         = Host.objects.get(kakao_id = host_kakao_id),
?!

2022-04-21 08:16 UTC, jamessoun93 approved these changes

2022-04-21 08:16 UTC, jamessoun93 commented on users/models.py
> +    def check_host(user):
```suggestion
    def check_host(self):
```

2022-04-21 08:16 UTC, jamessoun93 commented on spaces/views.py
> +            if not User.check_host(user):
```suggestion
            if not user.check_host():
```

2022-04-21 08:17 UTC, merged