[고현영] host convert view 작성
wecode-bootcamp-korea/31-2nd-GoCloud-backend pull request #4
Opened 2022-04-13 10:53 UTC by hy6652

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- host convert view 작성
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. user로 등록한 사용자가 host로 전환할 수 있는 기능을 추가했습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-04-13 13:01 UTC, bigfanoftim requested changes

2022-04-13 13:01 UTC, bigfanoftim commented on users/views.py
> +        )
중복 방지 로직이 추가되어야 할 것 같습니다!

2022-04-14 01:15 UTC, hy6652 commented
수정 했습니다!

2022-04-14 01:30 UTC, lordmyshepherd requested changes

2022-04-14 01:30 UTC, lordmyshepherd commented on users/views.py
> +        return HttpResponse(status = 201)
host 테이블에 보면 user_id를 제외하면 아무런 컬럼도 없네요. 

```python
class Host(TimeStamp): 
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='hosts')

    class Meta: 
        db_table = 'hosts'
```
지금 같은 기획에서는 host 테이블이 정말 필요한지 다시한번 고민해봐야 될 것 같습니다.
user가 host로 전환되면서 필요한 정보들이 추가로 있을 경우에만 테이블로 분리하는게 좋습니다.

host가 별도로 사용하는 email, phone number, address이 없는 지금과 같은 상황에서는 user table에 `is_host` coulmn만으로도 충분합니다.

테이블의 수가 적어지는 방향으로 설계하시기를 바랍니다!

2022-04-14 02:46 UTC, hy6652 commented
수정했습니다!

2022-04-14 06:26 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-04-14 06:26 UTC, merged